ref #3 Implement /metrics endpoint
simelo/rextporter pull request #9
Opened 2018-10-29 20:29 UTC by stdevAlDen

2018-10-31 17:57 UTC, stdevAlDen commented on test/integration/integration_test.go
> +	}
@simelo what do you think about this hack? I want to wait for the server to be started before start running the tests
and I prefer to wait three times for a second than a single time for three seconds.

2018-11-02 18:04 UTC, olemis requested changes

2018-11-02 18:04 UTC, olemis commented on examples/simple.toml
> +# [[hosts]]
Uncomment or delete .

2018-11-02 18:04 UTC, olemis commented on src/client/metric_client.go
>  type token struct {
Load from config .

2018-11-15 21:22 UTC, olemis approved these changes

2018-11-15 21:24 UTC, merged